name: final paper task 3


on:
  push:
    branches: [ main ]

jobs: 
  build-and-deploy-staticwebsite:
    
      name: staicweb
      runs-on: ubuntu-latest


      steps:
        - name: checkout
          uses: actions/checkout@v3
          
        - name: AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: eu-central-1

        - name: push to aws s3 bucket
          run: aws s3 sync . s3://www.task3.com